@echo off
chcp 65001 >nul
cd /d "%~dp0"
echo Stopping ETF Surge...
powershell -ExecutionPolicy Bypass -File "%~dp0stop.ps1" >nul 2>&1
echo Waiting for ports to free...
powershell -Command "try{ $ports=8000,5173; foreach($p in $ports){ $r=0; while($r -lt 15){ $c=netstat -ano|findstr \":$p \"; if(-not $c){ break }; sleep 1; $r++ } } }catch{}"
echo Starting ETF Surge...
powershell -ExecutionPolicy Bypass -File "%~dp0start.ps1" -Local -Silent
